### ISSUE TITLE
Negative margin shifts content

### ISSUE THREAD

**Issue by Spielboerg** [dfederm/karma-jasmine-html-reporter#38]
The element with the class `jasmine_html-reporter` has a margin of `-8px`. This results in the compiled components being pushed up into the gray box and the gray box is not 100% wide and leaves a small gap on the right side:

![Karma](https://user-images.githubusercontent.com/7893762/74742601-2b4c1a80-525f-11ea-85d4-9006505d4dfd.jpg)

It could easily be fixed by:
```css
body {
  margin: 0;
}

.jasmine_html-reporter {
  box-sizing: border-box;
  // margin: -8px;        // removing this line from the current CSS
}
```

I don't know if this change would break anything else.
